name: provider_starting_app
description: Starting point of a provider application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.0

  get_it: ^7.6.4
  provider: ^6.1.1

  dio: ^5.4.0
  dio_smart_retry: ^6.0.0

  json_annotation: ^4.8.1
  uuid: ^4.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  firebase_core: ^2.21.0
  firebase_analytics: ^10.7.0
  firebase_auth: ^4.12.1
  firebase_remote_config: ^4.3.3

  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - fonts/
    - assets/
    - assets/data/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic


        - asset: fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic


        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
